### ISSUE TITLE
Request: Make CSS background image path links a SASS variable

### ISSUE THREAD

**Issue by bbgvisualjournalist** [18F/web-design-standards#1007]
We're working on a Wordpress theme based on the web standards. 

The relative paths for background images are currently written like this: url('../img/arrow-down.png') 

This assumes that the CSS file is inside of a "/css" folder.

But Wordpress expects to see the CSS in the root folder of the theme (and uses the CSS to help define the theme).

Would it be possible to set the path for images as a SASS variable so that we can reference the images? (So that it's compatible with Wordpress or other systems in the future.)

Example: We need the above path to be:  url('img/arrow-down.png')

Many thanks.

**Comment by maya** [comment]
Hello @bbgvisualjournalist! That's a great question. Dealing with image paths for different asset pipelines is something that's definitely come up before and using a Sass variable to handle this is an interesting idea.

I could see us doing this with adding a Sass variable:

 ```
// Variable

$usa-image-path: ../img/;
```

To use this, we'd use [interpolation syntax](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_)

`background-image: url('#{$image-path}arrow-down.png')`

And then you'd only need to worry about setting the `$usa-image-path` variable for your use case.

Thoughts @msecret @rogeruiz @juliaelman?

**Comment by rogeruiz** [comment]
I think this is a good approach @maya. I like the idea of having variables for 
the `value` section. What about having `@mixins` for the `property` part as 
well? Something along the lines of:

```scss
@mixin usa-property-builder ( $prop, $value ) {
    $prop: $value;
}

body.ruby-on-rails {
    @include usa-property-builder( 
        background-color, 
        asset-path('#{usa-image-path}')
    );
}
```

This could go a long way to address some of the issues in 18f/us_web_design_standards_gem#15
