### ISSUE TITLE
List styling specificity issues

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1135]
Currently we style lists directly on the `ol, ul` element. Many people use lists for layout purposes, and while there is a `usa-unstyled-list` class to reset the list, it seems that people are not favoring that approach.

Some alternate ideas to remedy this:
1. Add a `usa-list` class for styled lists. The downside is that for someone just writing content, it will be a hassle to have to add classes every time.
2. Apply it directly to the list as it is now, but nest the class inside `usa-content` so it only effects parts that are intended to be written content.

Any other ideas?

**Comment by madmanlear** [comment]
I think your current approach is the right one, but here's how I solve that problem:

Whenever I use lists for layout I include additional, semantic markup. For example, a list of links with a specific layout will be wrapped in a nav, and globally any lists that are children of navs have stripped down styles. For example:

```css
ul,
ol {
  margin-left: 0;
  padding: 0 0 0 40px;
}

nav ul,
nav ol {
  list-style: none;
  list-style-image: none;
  margin: 0;
  padding: 0;
}
```

If that isn't acceptable, then I think your second solution is the way to go.
