### ISSUE TITLE
First child behavior different between usa-grid and usa-grid-full

### ISSUE THREAD

**Issue by jasonkaedingICE** [18F/web-design-standards#1768]
## Description

After upgrading from 0.8.x to 1.0, we observed some differences in the way padding/margin works for grids.  I think, in general, the direction is positive.  However, we have observed that usa-grid and usa-grid-full behave differently.

Quoting the standards website:

> To use a grid without padding on the right and left, use the usa-grid-full class instead.

We found in the CSS, the following sections:
````css
.usa-section > :first-child,
.usa-grid > :first-child {
  margin-top: 0;
}

.usa-section > :last-child,
.usa-grid > :last-child {
  margin-bottom: 0;
}
````

It seems odd that the usa-grid-full selectors weren't added here, given the description of the purpose is to remove left/right padding only.

## Code to demonstrate the difference

````html
<div class="usa-alert usa-alert-info">
  <div class="usa-alert-body">
    <h3 class="usa-alert-heading">Grid</h3>
	<p class="usa-alert-text">There should be no margin between this and the header inside the grid</p>
  </div>
</div>
<div class="usa-grid">
  <h2>In the grid</h2>
  <p></p>
</div>
<div class="usa-alert usa-alert-info">
  <div class="usa-alert-body">
    <h3 class="usa-alert-heading">Full Grid</h3>
    <p class="usa-alert-text">There is extra margin between this and the header inside the grid</p>
  </div>
</div>
<div class="usa-grid-full">
  <h2>In the "full" grid</h2>
  <p></p>
</div>
````
