### ISSUE TITLE
Simplifying styleguide's sidenav creation

### ISSUE THREAD

**Issue by nathand** [18F/web-design-standards#943]
I was trying to add pages to the sidenav, including sublists. Sublists are a bit tricky since you have to add an SCSS block to the styleguide.scss for every sublist you want to add to _includes/sidenav.html. I was able to get around that by doing the following.

Change the following lines in assets/css/styleguide.scss

```scss
.visual-style .sidenav .visual-style-sublist {
  display: block;

  ul {
    display: block;
  }
}

.form-controls .sidenav .form-controls-sublist {
  display: block;
}

.form-templates .sidenav .form-templates-sublist {
  display: block;
}

.footers .sidenav .footers-sublist {
  display: block;
}
```

to

```scss
a.usa-current + ul.usa-sidenav-sub_list {
  display: block;
}
```

This also removed the dependency on the body tag's classname
